# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-02 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioProfessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pub', models.DateField(verbose_name='Data de publicação')),
                ('texto', models.TextField()),
                ('pdf', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioSalaLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pub', models.DateField(verbose_name='Data de publicação')),
                ('texto', models.TextField()),
                ('pdf', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pub', models.DateField(verbose_name='Data de publicação')),
                ('texto', models.TextField()),
                ('pdf', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SalaLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='horarioturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Turma'),
        ),
        migrations.AddField(
            model_name='horariosalalab',
            name='salalab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.SalaLab'),
        ),
        migrations.AddField(
            model_name='horarioprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Professor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Professor'),
        ),
        migrations.AddField(
            model_name='horario',
            name='salalab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.SalaLab'),
        ),
        migrations.AddField(
            model_name='horario',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.Turma'),
        ),
    ]
